spring:
  application:
    name: db-dev-example
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3307/r_pan?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    h2:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: ""
    # 不设置默认的 spring.datasource.type，因为我们将通过配置类提供路由数据源
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true

db:
  dev:
    enabled: true
    ui-path: /db-dev
    sql:
      read-only: true
      max-rows: 500
    security:
      enabled: true
      username: admin
      password: 123456

server:
  port: 5555

logging:
  level:
    com.dbdev: DEBUG